# Generated by Django 5.1 on 2024-08-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joiningDate', models.DateField()),
                ('companyName', models.CharField(max_length=100)),
                ('managerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField()),
                ('workingHours', models.CharField(max_length=255)),
                ('probationPeriod', models.IntegerField()),
                ('watermark', models.ImageField(upload_to='watermarks/')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
