# Generated by Django 5.1 on 2024-09-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('companyName', models.CharField(max_length=255)),
                ('managerName', models.CharField(max_length=255)),
                ('performance', models.TextField()),
            ],
        ),
    ]
