# Generated by Django 5.1 on 2024-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_experienceletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewcallLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('interviewDate', models.DateField()),
                ('interviewTime', models.TimeField()),
                ('companyName', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(max_length=255)),
            ],
        ),
    ]
