# Generated by Django 5.1 on 2024-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_interviewcallletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('currentPosition', models.CharField(max_length=100)),
                ('newPosition', models.CharField(max_length=100)),
                ('effectiveDate', models.DateField()),
                ('salaryIncrement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('managerName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
    ]
