# Generated by Django 5.1 on 2024-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_promotionletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryIncreaseLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=255)),
                ('currentSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('newSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effectiveDate', models.DateField()),
                ('managerName', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
            ],
        ),
    ]
