# Generated by Django 5.1 on 2024-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_salaryincreaseletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('currentDepartment', models.CharField(max_length=100)),
                ('newDepartment', models.CharField(max_length=100)),
                ('newLocation', models.CharField(max_length=100)),
                ('effectiveDate', models.DateField()),
                ('managerName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
    ]
