# Generated by Django 5.1 on 2024-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_leaveapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('resignationDate', models.DateField()),
                ('lastWorkingDay', models.DateField()),
                ('managerName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
    ]
