# Generated by Django 5.1 on 2024-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_resignationletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('terminationDate', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('terminationReason', models.TextField()),
                ('finalDetails', models.TextField()),
                ('managerName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
    ]
