# Generated by Django 5.1 on 2024-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_separationagreementletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('issue_description', models.TextField()),
                ('warning_date', models.DateField()),
                ('consequences', models.TextField()),
                ('manager_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
    ]
