# Generated by Django 5.1 on 2024-09-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0012_performancereviewletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employmentPeriod', models.CharField(max_length=100)),
                ('managerName', models.CharField(max_length=100)),
                ('managerContact', models.CharField(max_length=20)),
                ('managerEmail', models.EmailField(max_length=254)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
    ]
