# Generated by Django 5.1 on 2024-09-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0013_referenceletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='probationPeriod',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='watermark',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='workingHours',
        ),
        migrations.AddField(
            model_name='offerletter',
            name='acceptance_deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='benefits',
            field=models.TextField(default='No benefits specified'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='department_name',
            field=models.CharField(default='Unknown Department', max_length=100),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='manager_name',
            field=models.CharField(default='Unknown Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='probation_period',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='report_manager',
            field=models.CharField(default='Unknown Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='salutation',
            field=models.CharField(default='Dear', max_length=10),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='working_hours',
            field=models.CharField(default='9 AM - 5 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
