# Generated by Django 5.1 on 2024-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0014_remove_offerletter_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='startDate',
        ),
        migrations.AddField(
            model_name='experienceletter',
            name='salutation',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerletter',
            name='start_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
